### PR TITLE
Merge session lens

### PR DESCRIPTION
**Pull request by rmagatti**
# Description

This PR is an attempt to merge https://github.com/rmagatti/session-lens with Auto Session.
So users of Session Lens functionality would only need to have auto-session and telescope installed and not yet another plugin.

Auto Session still works entirely without depending on Session Lens.

# Extra Features
- Toggling between two of the last restored/saved sessions

https://user-images.githubusercontent.com/2881382/230841466-4bf18849-03e4-487d-82e3-7e9dc40a1300.mov

### CODE REVIEW

**Comment by WieeRd** [comment]
@rmagatti This sounds like a great idea, but it looks like you haven't touched this for quite a while. Is there something stopping you from continuing/merging this PR? Is there anything I can help with?

**Comment by rmagatti** [comment]
Yeah, it's been a couple of weeks. Just haven't had the time to finish this up lately. I think the only thing missing is making the session-lens setup easier, right now since I imported it from the other plugin, it's `setup` separately, which I think is a crappy way of doing it. The behaviour I want is, you do `require("auto-session").setup {}` and if telescope is installed, session-lens gets setup with its defaults automatically. And if customization is needed, it should be done through auto-session's main config object passed into setup i.e
```lua
require("auto-session").setup {
  -- auto-session configs...
  session_lens = {
    ...session_lens_configs
  }
}
```

Aside from that the branch has been working fine, I've been using it as my daily driver since I first created it, but having other people test it out might be good too to increase my confidence level.

**Comment by rmagatti** [comment]
@WieeRd Actually, I've given this some more thought, this branch has a _lot_ of changes. I'll port whatever new things have made it into `main` and then make this branch essentially the v2 sometime soon.

**Comment by rmagatti** [comment]
Commit [82b6bc1](https://github.com/rmagatti/auto-session/pull/161/commits/82b6bc1be6fd182e04177712a10e9cd772ba9b68) has been tagged as `v2.0.0`. I'd appreciate folks testing this tag out. 

```lua
use {
  "rmagatti/auto-session",
  tag = "v2.0.0",
  config = function()
    require("auto-session").setup {
      log_level = vim.log.levels.ERROR,
      auto_session_suppress_dirs = { "~/", "~/Projects", "~/Downloads", "/" },
      auto_session_use_git_branch = false,
      auto_session_enable_last_session = false,

      session_lens = {
        theme_conf = { border = true },
        previewer = false,
      },
    }

    vim.keymap.set("n", "<C-s>", require("auto-session.session-lens").search_session, {
      noremap = true,
    })
  end,
}
```

This should get you started ^

**Comment by WieeRd** [comment]
I'm a bit late, but I can confirm this is working great :)  
Here are some of my thoughts and suggestions:  


**Do we need to keep the name `session-lens`?**

With 2 plugins now merged into 1,
The session search feature is more of a telescope integration than a separate module.  
I think changing the options/API names to just `telescope` sounds more straightforward.


**Default picker setting suggestions**

- Sort the sessions by their accessed date.
Having recently accessed at the top 
The current session should be an exception, which should have the lowest priority.
This'll make switching between 2 sessions as easy as `search_session()` + `<CR>`.

- Show `README.md` in the preview window, if it exists.
This might be a good default for `previewer = true` since sessions usually correspond to Git repos.

**Comment by rmagatti** [comment]
> Do we need to keep the name session-lens?
No, but I won't rename it in this branch, this has been a long-lived branch with quite a bit of scope creep already 😅. I'm down for renaming down the road for a more homogeneous experience!

> Sort the sessions by their accessed date
I have contemplated doing this before, tried it for a bit but it didn't pan out the way I wanted it to at the time. It may be a good future improvement though for sure!

> This'll make switching between 2 sessions as easy as search_session() + <CR>.
This, in particular, is already a feature btw, well not exactly like this, it currently works by calling the mapping `<C-s>` when a session-lens picker is open, auto-session keeps track of the previously restored session and can toggle between two sessions quickly.

> Show README.md in the preview window, if it exists.
This I'm not super sure about, not every project has a readme; other plugins preview the session file itself, which IMO is not super useful either. It could perhaps be a cool feature eventually, I'd certainly welcome a PR on this front!

Thanks a ton for the feedback btw, much appreciated!

**Pull request merged**
