### PR TITLE
Add config item to suppress load/save of session based on cwd.

### PR DESCRIPTION
**Pull request by WhoIsSethDaniel**

### CODE REVIEW

**Comment by WhoIsSethDaniel** [comment]
if you're okay with the basic idea I can add docs etc...

**Comment by WhoIsSethDaniel** [comment]
and I just noticed there is another PR with a similar idea.

**Comment by WhoIsSethDaniel** [comment]
I added some documentation in the README.

**Comment by rmagatti** [comment]
Ah yeah this looks pretty similar to https://github.com/rmagatti/auto-session/pull/16.

I think it's a cool feature to have, I'll check both approaches out.

**Comment by WhoIsSethDaniel** [comment]
> Looks pretty good overall. I've committed some suggestions on a separate branch let me know if those make sense.
> I'd basically move the suppress function out of the Lib file and into the main file, close to where the `is_enabled` function is.
> 
> Another change I did was using the configs when running the function, since when I tried starting Neovim with `nvim "+let g:auto_session_suppress_dirs = ['~/Projects/auto-session']"` it wasn't bypassing the session restoration. Grabbing config values when the function gets called solved that.
> 
> [Suggestions](https://github.com/WhoIsSethDaniel/auto-session/compare/suppress_by_dir...rmagatti:suppress_dir_suggestions)

I've rebased with your recent changes and added your suggestions. 

I looked at doing recursive suppression but even with only modestly deep directory trees it was very slow. At least the way I implemented it.  Perhaps there is a faster way.  So, for now, my implementation does exact match.  Perhaps pattern matching
would be better than globbing (which is what I tried).

**Comment by rmagatti** [comment]
I think exact match is likely enough for now, we can iterate if the need arises to do so. Thanks again for the PR man!

**Comment by Adictya** [comment]
Hey, sorry I didnt see this PR earlier. I think adding sub-folder matching via (*) operator could be a good feature, could you add that as well? Any other way to match subfolders would also work !

**Comment by WhoIsSethDaniel** [comment]
> Hey, sorry I didnt see the PR earlier. Im just starting out , could you tell why recursive matching using a * is not viable? Does it incur a performance penalty?

I think I'd like to wait until this PR is accepted.  I will then look at ways to do sub-folders.  Or you can, if you want.  For my part I really only need a few folders excluded from auto-session.

Of course, you can use vimscript (or similar lua functions) to create all directories you want excluded. So you can set 
```
let g:auto_session_suppress_dirs = expand('~/my/excluded/subdir/**', false, true)
```
I used to do this for gutentags (back when I used gutentags) since it had an exclude directory option, but it didn't support globs.

**Review by rmagatti — APPROVED** [review]

**Pull request merged**
