### PR TITLE
add feature for saving extra data to session

### PR DESCRIPTION
**Pull request by nanozuki**
Implemented #74

### CODE REVIEW

**Comment by nanozuki** [comment]
I can't ensure if this is duplicated to "post_restore". And I can't ensure if this is compatible with the vim function. Anyway, I think it is useful to allow "hook" to be a function that returns commands.

**Comment by rmagatti** [comment]
Hey, I've briefly looked into this PR, so sorry about the delay here. I'll try and look into it further this week, might even throw some improvements on here. One thing I'd like to mention is we'd want to update the readme and instructions on how to use this, or at least point to the helper files for session extra files.

**Comment by AbaoFromCUG** [comment]
hello,  I have new [commit](https://github.com/AbaoFromCUG/auto-session/commit/b4979da401453e347cbcafef4ac8c6dd294c02fc) , to complete this feature

> :help mks

> 10. If a file exists with the same name as the Session file, but ending in                                          "x.vim" (for eXtra), executes that as well.  You can use *x.vim files to
   specify additional settings and actions associated with a given Session,                                         such as creating menu items in the GUI version.

here is sample, when you restore session, neovim will load `{session_file}x.vim` automatically, for this case, echo 'hello world'
```lua
require('auto-session').setup {
    save_extra_cmds = {
        function()
            return [[echo "hello world"]]
        end
    }
}
```

should I open a new pull request? (I am newbee)

**Comment by rmagatti** [comment]
@AbaoFromCUG hey, I checked out your commit, it looks like that should work. I think _this_ PR just wasn't complete yet so we didn't merge it but your commit seems to check most of the boxes. You can open it up and we can discuss a few points I have in there. Thanks 🎉 and thanks to @nanozuki for putting the time a while back! (again sorry about the delay 😅)

**Comment by rmagatti** [comment]
#168 is merged, closing this, feel free to reopen if there's anything further!

**Pull request closed without merging**
