### PR TITLE
[Telescope Extension] Use custom picker instead of `find_files`

### PR DESCRIPTION
**Pull request by LukasPietzschmann**
Hi there :)
First of all, thank you for your work on this project! I was not sure if I should file this PR in this repo, or in [rmagatti/session-lens](https://github.com/rmagatti/session-lens), but as session-lens is also included in this repo, I decided to file it here (I hope that's fine for you).

As your telescope extension just uses the `find_files` picker internally, all settings set for this picker in telescope, e.g:
```lua
pickers = {
	find_files = {
		mappings = {
			i = { ['<CR>'] = actions.select_tab_drop }
		},
	},
}
```
also affect session-lens. The example above leads to undesirable and unexpected results (at least on my machine :D).

When creating a custom picker, settings won't bleed from telescopes pickers into session-lens, thus solving problems, like the one I mentioned above.

The only issue is that you now have to determine the `find_command` yourself (if the user did not set one). I "solved" this by just copying the code that telescope uses, but I don't think that this is a particularly elegant solution. It would be nice if telescope could determine the `find_command` and just give it to the extension. But I don't think that this is currently possible. Maybe you know a better way around that.

### CODE REVIEW

**Review by rmagatti — APPROVED** [review]
Hey, thanks for the PR!
Yeah I did some digging here and didn't find a better way to solve this. Good stuff!

**Comment by zyriab** [comment]
Hey, did this possibly broke stuff? Just started using this plugin today but it was not respecting my custom setting for Telescope HL groups. Also when passing custom options it did not respect them.
I check out the code but it's very late and can't start going down the rabbit hole.

I'll file an issue :)

**Comment by LukasPietzschmann** [comment]
Well, I only did limited testing before submitting the PR, but the things I checked for did indeed work.

I'll look into it. Give me a moment :)

**Comment by LukasPietzschmann** [comment]
Maybe it's smarter to look at your config first. Would you mind sharing it here?

**Comment by zyriab** [comment]
Hey @LukasPietzschmann thanks for the quick reply!
I've opened issue #267 where I explain everything and share my config.
I could totally be the culprit but it's really weird behavior!

**Pull request merged**
