### PR TITLE
revert filetype detect, save localoptions

### PR DESCRIPTION
**Pull request by zwhitchcox**
See https://github.com/rmagatti/auto-session/pull/179#issuecomment-1307567366

Save local options which will restore syntax highlighting, as well as `wrap` and `number` options

### CODE REVIEW

**Review by rmagatti — APPROVED** [review]

**Comment by MikaelElkiaer** [comment]
@rmagatti @zwhitchcox 

I'd call this a breaking change, took me some time figuring out why my session switching was breaking.
Had to `:e` the first file every time I switched sessions, and in general just had weird behaviour.

@rmagatti Perhaps you could create a pinned issue with breaking changes like these? - For easy subscription.

**Comment by rmagatti** [comment]
I can create that issue for sure! I'm still unclear on what was breaking from this change as merely the defer function was removed that didn't actually even exist before if I'm not mistaken. Either way a breaking change issue is a great idea, thanks!

**Comment by rmagatti** [comment]
@MikaelElkiaer here it is:
https://github.com/rmagatti/auto-session/issues/186

**Comment by MikaelElkiaer** [comment]
> I can create that issue for sure! I'm still unclear on what was breaking from this change as merely the defer function was removed that didn't actually even exist before if I'm not mistaken. Either way a breaking change issue is a great idea, thanks! 

There might be more to it then than just this.

My syntax highlighting was gone whenever I would restore a session, until after adding the `localoptions` bit to restore options.

**Comment by zwhitchcox** [comment]
@MikaelElkiaer Sorry this gave you so much trouble, but I would not classify this as a breaking change. `auto-session` was just covering up a misconfiguration (not saving `localoptions`) with an ugly hack where it would delay the restoration of the session by 50 ms.

Aside from the race condition bugs this could cause, it also introduced a scenario where if the session restoration caused the directory to change, this would cause a new session restoration, which could cause the directory to change again, ad infinitum.

The syntax highlighting is a lower priority than the infinitely recursive directory changes.

That being said, I do think we could make it easier to figure out than combing through issues/PRs. It might be nice to add the `localoptions` note to the trouble shooting page on the wiki @rmagatti ...or maybe just add it as a note in the readme?

I could also just add this change back in, because it would not hurt anything other than slightly decreasing performance, but it might provide a better UX for some users.

**Comment by rmagatti** [comment]
The readme does recommend adding `localoptions` to `sessioniptions` already. It just doesn't really say what that does or doesn't do. Maybe this is a common enough occurrence that it might be worth explaining further in the readme, but maybe it's easier to tell people to `:h sessionoptions` in case they want to know what each of the recommended options (and others) do for session loading. I'll add something to the readme on this (unless one of you want to 😄)

**Comment by zwhitchcox** [comment]
How about we just say if more people comments on this saying that it gave them trouble we can add more documentation, but otherwise count this as documentation

**Pull request merged**
