### PR TITLE
Bypass on only buffer of specific file types

### PR DESCRIPTION
**Pull request by rmagatti**
Attempt to address #69

### CODE REVIEW

**Comment by glyh** [comment]
I have trouble get this working, not sure if my configuration is correct though:
To reproduce:
1. save [this gist](https://gist.github.com/glyh/82247c7de6e08336ef84996dedb2a80d) as test.lua.
2. `touch /tmp/a.py`, `touch b.lua` to create some test files.
3. `nvim -nu test.lua`, to install the plugins. then open a.py and b.lua.
4. `qa!` to quit, then `nvim -nu test.lua` to call up neovim again.

Observed behavior: all buffers are restored (please ignore the buffer generate by packer because of updating plugins)

**Comment by rmagatti** [comment]
I think you might be misunderstanding how this works. My fault actually because I didn't add a readme entry yet.
This won't stop a specific buffer from being saved, it can't in fact. What this does is check if the only buffer currently open is of a particular file type it then does not save a session.

This is intended to be used for things like dashboard or startify buffers where there's no point in saving a session when those are the only buffers open.

**Comment by glyh** [comment]
Could you provide an example configuration? Thanks!

**Comment by rmagatti** [comment]
With this config example, when one has only one buffer of filetype markdown open, a session will not be saved. Not very useful, but just an example.

I don't use "dashboard" plugins myself so I'm not sure what filetypes those usually use, all one would have to do is add the filetype to the list here though.

```
require("auto-session").setup {
  log_level = "info",
  bypass_session_save_file_types = { "markdown" },
}
```

**Comment by glyh** [comment]
How is this different from the gist I use? copied from there:
```lua
            { 'rmagatti/auto-session',
              branch = 'bypass-auto-save-file-types',
              config = function()
                require('auto-session').setup { 
                  log_level = 'info',
                  bypass_session_save_file_types = {"lua"}
                }
              end,
              -- disable = true
            }

```

**Comment by glyh** [comment]
Sry for my misunderstanding, I've tested, it works.

**Pull request merged**
