### PR TITLE
Session filename completion

### PR DESCRIPTION
**Pull request by WhoIsSethDaniel**
When deleting sessions allow the user to use
completion to find the right session to delete.

### CODE REVIEW

**Comment by WhoIsSethDaniel** [comment]
I really wanted to be able to cleanup the file names when they are displayed, but if this is possible I can't figure it out. This is the next best thing. I know session-lens can delete sessions but, for simple cases, I prefer using :DeleteSession with completion.

**Review by rmagatti — APPROVED** [review]

**Comment by rmagatti** [comment]
Hey I like this, so `Telescope` has a `path_shorten` function I use in `session-lens`.

[Session lens](https://github.com/rmagatti/session-lens/blob/a486ef7894ccfd3b28fb82c26bad786d96798dda/lua/telescope/_extensions/session-lens/session-lens-library.lua#L103)
[Telescope](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/path.lua#L23)

Maybe we can use the implementation telescope uses to shorten the completion path? It would show similar to how it shows in session-lens.

**Comment by WhoIsSethDaniel** [comment]
> Hey I like this, so `Telescope` has a `path_shorten` function I use in `session-lens`.
> 
> [Session lens](https://github.com/rmagatti/session-lens/blob/a486ef7894ccfd3b28fb82c26bad786d96798dda/lua/telescope/_extensions/session-lens/session-lens-library.lua#L103)
> [Telescope](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/path.lua#L23)
> 
> Maybe we can use the implementation telescope uses to shorten the completion path? It would show similar to how it shows in session-lens.

I will look at that.

**Comment by WhoIsSethDaniel** [comment]
The path_shorten function uses ffi and I'm not terribly familiar with that, at least as it applies to lua.  I'm hesitant to cargo cult this function. 
I think a potentially just as good way is to use fnamemodify to get the file name without directory, and unencode the slashes. This should give the actual path the session file represents.  This would also require the opposing actions so that we have something to pass to AutoSession.DeleteSession. 
A simple flow might be:
1) user presses <tab> while using :DeleteSession
2) slurp up all session files, extract just the filenames and unencode the slashes. display the results.
3) user selects one or more session files
4) selections are passed to some function which re-encodes and re-appends the full path
5) result of 4 is passed to AutoSession.DeleteSession

One consequence of this is that :DeleteSession would not be able to delete a session file if the raw path is passed to it since it won't be expecting that. We could attempt to distinguish raw session paths from the other form. Or two commands could be created: one for deleting via raw session path (:DeleteRawSession) and the other via the cleaner path.  Or raw session paths can be ignored. Who wants to deal with those anyway?

**Comment by rmagatti** [comment]
Yeah either way I think this can be improved in a subsequent PR. The current behaviour already works pretty well. We can merge this if you think it's ready.

**Review by rmagatti — APPROVED** [review]

**Comment by WhoIsSethDaniel** [comment]
> Yeah either way I think this can be improved in a subsequent PR. The current behaviour already works pretty well. We can merge this if you think it's ready.

It should be merged.

**Comment by kthenrique** [comment]
@rmagatti, @WhoIsSethDaniel, Could we also have this completion set for the **RestoreSession** command, please?

**Comment by rmagatti** [comment]
Should be easy enough to add @kthenrique. I'd welcome a PR for it!

**Comment by WhoIsSethDaniel** [comment]
I've added PR #120. Let's see what happens.

**Pull request merged**
