### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by cameronr**
I saw your comments from a while back about wanting to clean the code up and I figured getting some unit tests would be a good first step. There's still a lot of stuff that isn't covered but I wanted to make sure you're ok with the general approach. thanks!

### CODE REVIEW

**Comment by cameronr** [comment]
Also, I recently saw https://www.conventionalcommits.org/en/v1.0.0/ and I'm into to it so going to start writing my commits that way.

**Comment by cameronr** [comment]
Sorry that this PR has gotten big!

**Review by rmagatti — APPROVED** [review]
This is some great work adding tests here. Thank you so much for the time dedicated to this! 🥹

**Comment by rmagatti** [comment]
> Also, I recently saw https://www.conventionalcommits.org/en/v1.0.0/ and I'm into to it so going to start writing my commits that way.

Perfect, I'm a big fan too. Haven't always followed it but starting to more now for sure. Plus lazy.nvim reads conventional commit breaking changes syntax to let the user know a breaking change has been added for example, really cool

**Pull request merged**
